<a href="https://colab.research.google.com/github/AdewaleOpeloyeru/learnpytorch/blob/colab-commits/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [2]:
print("Hello. I'm excited to learn PyTorch!")

Hello. I'm excited to learn PyTorch!


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


## Introduction to Tensors
### Creating Tensors
PyTorch tensors are created using torch.Tensor() ==> https://docs.pytorch.org/docs/stable/tensors.html

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
# Get tensor back as python int
scalar.item() # returns scalar equivalent. doesn't work with tensors of dimension greater than 0

7

In [7]:
scalar.ndim    #ndim = dimension

0

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim   # ndim contains how many dimensions a tensor has. e.g vector only has columns so it has 1 dimension

1

In [10]:
vector.shape    # Returns how many elements are in each dimension. i.e; we have 2 elements in vector

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7, 8],[9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim     # i.e we have rows and columns

2

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape          # 2 element per row and 2 elements per column

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
# Note that a tensor can have any dimension. A matrix/tensor is usually defined as uppercase letters
MYTENSOR =  torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                          [[-1,-2,-3],
                           [-3,-6,-3],
                           [-2,-4,-5]]])
MYTENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  5]],

        [[-1, -2, -3],
         [-3, -6, -3],
         [-2, -4, -5]]])

In [20]:
MYTENSOR.ndim

3

In [21]:
MYTENSOR.shape

torch.Size([2, 3, 3])

### Random Tensors

WHy random tensors?

Random tensors are important because the way many neural networks learn is that the strat with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

random tensors: https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [22]:
# Create random tensor of  size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5001, 0.3549, 0.8998, 0.3472],
        [0.5676, 0.5877, 0.1550, 0.7286],
        [0.4588, 0.1250, 0.1759, 0.8989]])

In [23]:
random_tensor.ndim

2

In [24]:
ANOTHERTENSOR = torch.rand(10,10,10)
ANOTHERTENSOR

tensor([[[9.9666e-01, 9.1534e-01, 7.7715e-01, 2.3580e-02, 4.8779e-01,
          9.6265e-02, 2.2799e-01, 1.3748e-01, 4.6462e-01, 6.4075e-01],
         [1.7868e-01, 1.8271e-01, 5.9061e-01, 8.3358e-01, 4.4005e-02,
          9.5508e-01, 1.1001e-01, 8.7193e-01, 8.4906e-01, 5.6221e-02],
         [7.6103e-01, 2.0505e-03, 6.3454e-01, 6.4920e-01, 2.6373e-01,
          5.9842e-01, 1.0792e-01, 3.7804e-01, 6.7464e-01, 9.8723e-01],
         [5.3909e-01, 8.6538e-01, 4.6212e-02, 3.2432e-01, 6.3113e-01,
          6.0870e-01, 6.2809e-02, 8.1268e-01, 8.2388e-02, 6.5300e-02],
         [1.8426e-01, 7.5089e-01, 7.4608e-01, 8.6247e-02, 6.9295e-01,
          5.3974e-01, 8.0321e-01, 2.3491e-01, 2.3760e-01, 9.2903e-01],
         [3.7268e-01, 5.6986e-01, 5.3770e-02, 8.8590e-01, 7.6792e-01,
          3.5880e-01, 9.1801e-01, 3.4982e-01, 7.3290e-01, 9.6115e-01],
         [5.3818e-01, 1.0609e-01, 9.4937e-01, 7.2169e-01, 5.9795e-01,
          8.4015e-01, 1.3057e-01, 2.6832e-01, 8.6071e-01, 4.4387e-01],
         [4.8

In [25]:
ANOTHERTENSOR.ndim, ANOTHERTENSOR.shape

(3, torch.Size([10, 10, 10]))

In [26]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channel
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [27]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype     # .dtype returns the datatype of a tensor. tensors in pytoch are of type torch.float32 by default

torch.float32

### Creating a range of tensors and tensors-like

In [30]:
# Use torch.range()
torch.range(0,10)

/tmp/ipython-input-3858421243.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
# Use torch.arange() ==> takes ame arguments like range() in python
tensor_range=torch.arange(1,10,2)
tensor_range

tensor([1, 3, 5, 7, 9])

In [35]:
# creating tensors like ==> used to create tensors of the same shape as a given tensor
tensor_range_shape_zeros = torch.zeros_like(tensor_range)
tensor_range_shape_zeros


tensor([0, 0, 0, 0, 0])

### Tensor datatypes
Understanding tensor datatypes is very important because it is one of the 3 big errors that is often encountered with pytorch and deep learning.

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

Data types docummentation: https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch.dtype


In [36]:
# Float 32 tensor.
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, # tensors are of type torch.float32 by default
                                device=None,  # what device is the tensor on? cpu, gpu, tpu, cuda, etc.
                                requires_grad=False # track gradients with this tensor
                                )
float_32_tensor

tensor([3., 6., 9.])

In [37]:
float_32_tensor

tensor([3., 6., 9.])

In [38]:
# convert float_32_tensor to a tensor of type torch.float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [41]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [46]:
complex_tensor = torch.tensor([3-1j, 6+2j, 9j],
                                dtype=None,
                                device=None,
                                requires_grad=False
                                )
complex_tensor

tensor([3.-1.j, 6.+2.j, 0.+9.j])

In [47]:
complex_tensor.dtype

torch.complex64

In [48]:
# 2.06.57