<a href="https://colab.research.google.com/github/AdewaleOpeloyeru/learnpytorch/blob/colab-commits/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
print("Hello. I'm excited to learn PyTorch!")

Hello. I'm excited to learn PyTorch!


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


## Introduction to Tensors
### Creating Tensors
PyTorch tensors are created using torch.Tensor() ==> https://docs.pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Get tensor back as python int
scalar.item() # returns scalar equivalent. doesn't work with tensors of dimension greater than 0

7

In [ ]:
scalar.ndim    #ndim = dimension

0

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim   # ndim contains how many dimensions a tensor has. e.g vector only has columns so it has 1 dimension

1

In [ ]:
vector.shape    # Returns how many elements are in each dimension. i.e; we have 2 elements in vector

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],[9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim     # i.e we have rows and columns

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape          # 2 element per row and 2 elements per column

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
# Note that a tensor can have any dimension. A matrix/tensor is usually defined as uppercase letters
MYTENSOR =  torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                          [[-1,-2,-3],
                           [-3,-6,-3],
                           [-2,-4,-5]]])
MYTENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  5]],

        [[-1, -2, -3],
         [-3, -6, -3],
         [-2, -4, -5]]])

In [ ]:
MYTENSOR.ndim

3

In [ ]:
MYTENSOR.shape

torch.Size([2, 3, 3])

### Random Tensors

WHy random tensors?

Random tensors are important because the way many neural networks learn is that the strat with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

random tensors: https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create random tensor of  size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5933, 0.8453, 0.5979, 0.2181],
        [0.0079, 0.5271, 0.9030, 0.8595],
        [0.7496, 0.2853, 0.5519, 0.0935]])

In [ ]:
random_tensor.ndim

2

In [ ]:
ANOTHERTENSOR = torch.rand(10,10,10)
ANOTHERTENSOR

tensor([[[1.0344e-01, 4.8324e-01, 1.4467e-01, 7.2122e-01, 3.4928e-01,
          9.5945e-01, 4.1775e-01, 7.6242e-01, 3.9211e-01, 2.9819e-01],
         [3.0680e-01, 2.3958e-02, 9.1486e-01, 4.1943e-01, 2.7836e-01,
          9.2735e-01, 2.1531e-02, 9.8735e-01, 8.8240e-01, 3.4802e-01],
         [8.0979e-01, 2.1550e-01, 1.3826e-01, 8.5079e-01, 9.0384e-02,
          2.7573e-01, 9.0470e-01, 9.6304e-01, 3.5740e-01, 9.8255e-01],
         [2.6678e-01, 1.9365e-01, 9.6012e-01, 7.7442e-01, 3.9500e-01,
          2.5676e-01, 7.6870e-01, 6.8388e-02, 6.2189e-01, 4.9991e-01],
         [3.9692e-01, 9.9793e-01, 3.1264e-01, 2.7907e-01, 4.6707e-02,
          9.9125e-01, 2.6885e-01, 3.5974e-01, 9.2896e-02, 3.0599e-01],
         [7.6029e-01, 7.7979e-01, 9.8129e-01, 2.1413e-02, 2.7764e-01,
          4.6556e-01, 8.1116e-01, 9.6362e-01, 2.2909e-01, 9.9457e-01],
         [6.4712e-01, 5.4648e-01, 9.6667e-02, 4.6998e-01, 2.1194e-02,
          6.6507e-01, 2.9557e-01, 6.5131e-01, 6.2611e-01, 1.4459e-02],
         [3.0

In [ ]:
ANOTHERTENSOR.ndim, ANOTHERTENSOR.shape

(3, torch.Size([10, 10, 10]))

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channel
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype     # .dtype returns the datatype of a tensor. tensors in pytoch are of type torch.float32 by default

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()
torch.range(0,10)

/tmp/ipython-input-3858421243.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# Use torch.arange() ==> takes ame arguments like range() in python
tensor_range=torch.arange(1,10,2)
tensor_range

tensor([1, 3, 5, 7, 9])

In [ ]:
# creating tensors like ==> used to create tensors of the same shape as a given tensor
tensor_range_shape_zeros = torch.zeros_like(tensor_range)
tensor_range_shape_zeros


tensor([0, 0, 0, 0, 0])

### Tensor datatypes
Understanding tensor datatypes is very important because it is one of the 3 big errors that is often encountered with pytorch and deep learning.

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

Data types docummentation: https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch.dtype


In [ ]:
# Float 32 tensor.
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, # tensors are of type torch.float32 by default
                                device=None,  # what device is the tensor on? cpu, gpu, tpu, cuda, etc.
                                requires_grad=False # track gradients with this tensor
                                )
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
# convert float_32_tensor to a tensor of type torch.float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
complex_tensor = torch.tensor([3-1j, 6+2j, 9j],
                                dtype=None,
                                device=None,
                                requires_grad=False
                                )
complex_tensor

tensor([3.-1.j, 6.+2.j, 0.+9.j])

In [ ]:
complex_tensor.dtype

torch.complex64

In [ ]:
complex_tensor * float_16_tensor

tensor([ 9.-3.j, 36.+12.j,  0.+81.j])

In [ ]:
# 2.06.57

### Getting information from tensors
datatype --> tensor.dtype


shape --> tensor.shape


device --> tensor.device

In [ ]:
# create a tensor
some_tensor = torch.rand(size=(3,4))
some_tensor

tensor([[0.0044, 0.4734, 0.6088, 0.3704],
        [0.3702, 0.9224, 0.7828, 0.2308],
        [0.3596, 0.3843, 0.5676, 0.4891]])

In [ ]:
# Find details about the tensor
print(some_tensor)
print(f"datatype of tensore: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"device tensor is on: {some_tensor.device}")
# zhape can also be determined using size() function
print(f"shape of tensor using size: {some_tensor.size()}")

tensor([[0.0044, 0.4734, 0.6088, 0.3704],
        [0.3702, 0.9224, 0.7828, 0.2308],
        [0.3596, 0.3843, 0.5676, 0.4891]])
datatype of tensore: torch.float32
shape of tensor: torch.Size([3, 4])
device tensor is on: cpu
shape of tensor using size: torch.Size([3, 4])


In [ ]:
another_tensor = torch.rand(size=(3,4),
                            dtype=torch.complex64,
                            device="cpu")
another_tensor

tensor([[0.7607+0.8374j, 0.7889+0.8419j, 0.8623+0.0875j, 0.9633+0.4404j],
        [0.2079+0.3967j, 0.5617+0.4669j, 0.1358+0.4644j, 0.3936+0.8932j],
        [0.1651+0.2747j, 0.3026+0.4833j, 0.8761+0.4949j, 0.2880+0.0238j]])

### Manipulating Tensors (tensor operation)
Operations include:
* Addition
* subtraction
* Multiplication
* Division
* Matrix multiplication


In [ ]:
# Addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiplication
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtraction
tensor - 10

tensor([-9, -8, -7])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
# pytorch also has inbuilt functions to perform this operations
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [ ]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication (dot product)
more info here: https://www.mathsisfun.com/algebra/matrix-multiplying.html

#### rules of multiplication
* you can only multiply an AxN by NxB matrix.
* this will result in AxB matrix



In [ ]:
# elementwise multiplication
print(tensor, "*", tensor)
print(f"Equals:{tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
# @ operator stands for matrix multiplication
tensor @ tensor

tensor(14)

In [ ]:
# %%time jupiter command to get time taken for an operation to complete. %time calculates for a single line
%%time
torch.matmul(tensor, tensor) # internally, one of the matrices is transposed to a single column matrix before multiplying

CPU times: user 626 µs, sys: 0 ns, total: 626 µs
Wall time: 529 µs


tensor(14)

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B)  # torch.mm() is an alias for torch.matmul
# This multiplication won't work because both tensors are 3x2
#RuntimeError                              Traceback (most recent call last)
#/tmp/ipython-input-3379101801.py in <cell line: 0>()
#      5                          [8,11],
#      6                          [9,12]])
#----> 7 torch.mm(tensor_A, tensor_B)  # torch.mm() is an alias for torch.matmul
#
#RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# to fix, we transpose one of the tensors using .T
print(torch.mm(tensor_A, tensor_B.T))
print("\nshape of result:", torch.mm(tensor_A, tensor_B.T).shape)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

shape of result: torch.Size([3, 3])


### Tensor Aggregation
#### Finding the min, max, mean, sum, etc

In [ ]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# min
torch.min(x), x.min(), min(x)


(tensor(0), tensor(0), tensor(0))

In [ ]:
# max
torch.max(x), x.max(), max(x)


(tensor(90), tensor(90), tensor(90))

In [ ]:
# mean or average
# torch.mean() only works with complex or floatdtypes
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean(),


(tensor(45.), tensor(45.))

In [ ]:
# sum
torch.sum(x), x.sum(), sum(x)

(tensor(450.), tensor(450.), tensor(450.))

In [ ]:
# 2:54:32

### Finding the position of min and max

In [131]:
x.argmin()     #--> returns the index of the min value

tensor(0)

In [132]:
x.argmax()

tensor(9)

### Reshaping, stacking, squezzing and unsqueezing tensors

* Reshaping --> reshapes an input tensor to a defined shape
* View --> return a view of an input tensor of certain shape but keep the same memory as original tensor
* Stacking --> combine multiple tensors on top of ecah other (vstack) or side by side (hstack)
* Squeeze --> removes all 1 dimension from a tensor
* Unsqueeze --> add a 1 dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [153]:
# Let's start over
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [154]:
# Reshape
# x_reshaped = x.reshape(1, 7) --> would fail because the only dimension we have has 9 elements
# for reshape to succeed the elements available must fit into the new shape
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [155]:
#x_reshaped = x.reshape(9, 1)
#x_reshaped, x_reshaped.shape

In [156]:
another_x = torch.arange(1., 11.)
another_x, another_x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [157]:
another_x_reshaped = another_x.reshape(5, 2)
another_x_reshaped, another_x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [158]:
another_x_reshaped = another_x.reshape(2, 5)
another_x_reshaped, another_x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [159]:
# View
z = x.view(1,9)    # --> z will use the same memory as x. any operation on the view of tensor will also affect the tensor
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [160]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [161]:
# Stacking
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [162]:
_stacked = torch.vstack([x,x,x,x])   # vertical stacking
_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [163]:
_stacked = torch.hstack([x,x,x,x])   # horizontal
_stacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [164]:
# Squize -->  Removes dimension 0f size 1 from a given tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [165]:
x_reshaped.shape

torch.Size([1, 9])

In [171]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [172]:
x_squeezed.shape

torch.Size([9])

In [179]:
# Unsqueeze --> adds a single dimension to a tensor at the specified dimension
print(f"previous targer: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous targer: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [180]:
# Permute   --> rearranges elements in a tensor to follow a given order of dimensions
x_original = torch.rand(224, 224, 3)     # sample image tensor [height, width, colour_channels]

x_permuted = x_original.permute(2,0,1)
print(f"original shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")



original shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [184]:
# Note that the permute version of a tensor shares the same memory with the original tensor
print(x_original)
print(x_permuted)
x_original[0,0,0] = 1988
print(x_original)
print(x_permuted)

tensor([[[0.2026, 0.8173, 0.6304],
         [0.2889, 0.1671, 0.7271],
         [0.5270, 0.1442, 0.8393],
         ...,
         [0.2234, 0.0578, 0.8755],
         [0.4726, 0.4012, 0.6869],
         [0.6241, 0.9666, 0.1797]],

        [[0.6108, 0.0788, 0.9194],
         [0.2595, 0.4983, 0.2864],
         [0.2705, 0.5869, 0.2517],
         ...,
         [0.7901, 0.7791, 0.6750],
         [0.4902, 0.0869, 0.6636],
         [0.2607, 0.8363, 0.8085]],

        [[0.4613, 0.0514, 0.5257],
         [0.8321, 0.4896, 0.7321],
         [0.7747, 0.9931, 0.8849],
         ...,
         [0.2269, 0.6474, 0.5207],
         [0.2921, 0.6749, 0.7531],
         [0.4540, 0.8112, 0.1473]],

        ...,

        [[0.7259, 0.8024, 0.4644],
         [0.7709, 0.4214, 0.8984],
         [0.8791, 0.4257, 0.5577],
         ...,
         [0.1459, 0.9984, 0.4070],
         [0.3322, 0.9792, 0.9098],
         [0.9637, 0.4154, 0.8487]],

        [[0.8746, 0.7339, 0.5055],
         [0.0759, 0.7148, 0.4026],
         [0.