<a href="https://colab.research.google.com/github/AdewaleOpeloyeru/learnpytorch/blob/colab-commits/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [2]:
print("Hello. I'm excited to learn PyTorch!")

Hello. I'm excited to learn PyTorch!


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


## Introduction to Tensors
### Creating Tensors
PyTorch tensors are created using torch.Tensor() ==> https://docs.pytorch.org/docs/stable/tensors.html

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
# Get tensor back as python int
scalar.item() # returns scalar equivalent. doesn't work with tensors of dimension greater than 0

7

In [7]:
scalar.ndim    #ndim = dimension

0

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim   # ndim contains how many dimensions a tensor has. e.g vector only has columns so it has 1 dimension

1

In [10]:
vector.shape    # Returns how many elements are in each dimension. i.e; we have 2 elements in vector

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7, 8],[9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim     # i.e we have rows and columns

2

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape          # 2 element per row and 2 elements per column

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [22]:
# Note that a tensor can have any dimension. A matrix/tensor is usually defined as uppercase letters
MYTENSOR =  torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                          [[-1,-2,-3],
                           [-3,-6,-3],
                           [-2,-4,-5]]])
MYTENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  5]],

        [[-1, -2, -3],
         [-3, -6, -3],
         [-2, -4, -5]]])

In [20]:
MYTENSOR.ndim

3

In [21]:
MYTENSOR.shape

torch.Size([2, 3, 3])

### Random Tensors

WHy random tensors?

Random tensors are important because the way many neural networks learn is that the strat with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

random tensors: https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [23]:
# Create random tensor of  size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0239, 0.6480, 0.0286, 0.8837],
        [0.5510, 0.8512, 0.1899, 0.8131],
        [0.0839, 0.1943, 0.3189, 0.0114]])

In [24]:
random_tensor.ndim

2

In [25]:
ANOTHERTENSOR = torch.rand(10,10,10)
ANOTHERTENSOR

tensor([[[0.8468, 0.1809, 0.5701, 0.7096, 0.5840, 0.7439, 0.7491, 0.2314,
          0.7366, 0.6903],
         [0.3360, 0.5056, 0.4014, 0.1540, 0.8997, 0.8774, 0.0740, 0.4133,
          0.5382, 0.0350],
         [0.1448, 0.9719, 0.3960, 0.7346, 0.7426, 0.2328, 0.3487, 0.5473,
          0.3868, 0.4794],
         [0.5355, 0.6351, 0.8234, 0.7413, 0.3002, 0.3978, 0.3310, 0.4348,
          0.1535, 0.7622],
         [0.9557, 0.9417, 0.4846, 0.6911, 0.6639, 0.0828, 0.0308, 0.3405,
          0.5908, 0.9159],
         [0.7053, 0.6634, 0.6068, 0.8975, 0.4516, 0.8334, 0.9039, 0.2500,
          0.5264, 0.4144],
         [0.0366, 0.7978, 0.7620, 0.1935, 0.0637, 0.7047, 0.4282, 0.0201,
          0.7632, 0.7482],
         [0.5326, 0.0444, 0.7059, 0.2973, 0.0583, 0.4168, 0.6002, 0.0478,
          0.7040, 0.1692],
         [0.5067, 0.7791, 0.8887, 0.9624, 0.2155, 0.2252, 0.9183, 0.8110,
          0.9581, 0.8503],
         [0.2356, 0.2585, 0.1747, 0.0373, 0.5084, 0.4108, 0.6253, 0.2463,
          0.9499,

In [28]:
ANOTHERTENSOR.ndim, ANOTHERTENSOR.shape

(3, torch.Size([10, 10, 10]))

In [26]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channel
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)